### ISSUE TITLE
dnsmasq.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by wimmerX** [felixonmars/dnsmasq-china-list#398] opened 2022-04-14 05:37 UTC
sudo ./install.sh后，重启dnsmasq timeout error。删除几个/etc/dnsmasq.d/下的conf文件，可以成功，请问dnsmasq会限制加载的.conf数量么？这个如何调整？

**Comment by fernvenue** [comment] 2022-04-14 06:00
Duplicate of https://github.com/felixonmars/dnsmasq-china-list/issues/227.

**Closed** 2022-05-14 08:13 UTC
